### ISSUE TITLE
Not updated?

### ISSUE THREAD

**Issue by eitsupi** [r-hub/rversions.app#20]
https://rversions.r-pkg.org/r-versions
Currently the json response appears to only include up to R4.1.2.
Has it been updated since the R4.1.3 release?

**Comment by gaborcsardi** [comment]
Consider using https://api.r-hub.io/rversions instead.

**Comment by eitsupi** [comment]
Thank you for your prompt reply. Works nice! https://api.r-hub.io/rversions/r-versions
It would be easier to understand if you could rewrite the link from the repository to that.

![image](https://user-images.githubusercontent.com/50911393/166971231-3495131b-c55d-4ecc-8673-742664125e68.png)
